### ISSUE TITLE
Setup support

### ISSUE THREAD

**Issue by buitre-buitaker** [j-be/rust-streamium#1]
Do you provide any support on this project?

I am quite interested on it.

Thank you!

**Comment by j-be** [comment]
Hey,

yeah, sure. I thought I was the last human on earth having one of those devices, so I never bothered writing a decent README. Turns out I was wrong... :smiley:

Give me a few hours/days, and I'll write up something.

**Comment by j-be** [comment]
Done.

Please go through the `README.md`. If there are unanswered questions, or I missed a step, please reopen this issue.

Enjoy :smile:

**Comment by buitre-buitaker** [comment]
Hi again Juri,

Thank you very much for the extensive and detailed instructions.

I am trying your setup it in a raspberry pi, and I am trying to emulate a Streamium center, to stream MP3 files to three satellites that I have (WAS6050). My Streamium center is complety broken. No way to repair it. 

I setup all the things, but I have two issues:

- when I click the reflesh button, it doesn't import the MP3 files to the database, how can I check this process to guess the problem?
- I press the "Music HD" button in my satellite, it is supposed to scan the network for a Streamium Center, but it didn't find the server. How can I check if the server gets the udp broadcasts from the satellites?

I don't know if it is possible to generate a log file in your streamium server.

Thank you!

**Comment by j-be** [comment]
Hey,

about your setup: That should work, I'm running a quite similar one here at home. Debugging it remotely will be difficult, but that makes it nothing but more interesting :smile: 

About the **import**: that part is completely silent, i.e. it does not show any status. It also doesn't log anything, except for errors. Though, when the import finished, you should see the files appearing in the "Artist" section of the WebUI. I am not sure, whether the list shows something while the import is running - I will check that and come back to you.

While writing this, it came to my mind: please also make sure the user, which is running the server (if you followed my README that would be `streamium`) has access to your media files and can read them:
```
sudo su streamium -s /bin/bash
cd /path/to/your/music/collection
ls -la
```
Make sure all files are other-readable and all folders carry the `x` flag in the "others" section.

If you open the WebUI and see the below, that at least tells us, that the setup is correct and that the server can read/write to and from database - even the toplevel entries are in database:
![image](https://user-images.githubusercontent.com/8503582/79052918-f0041180-7c39-11ea-900b-cfacc4477d51.png)

If you only see the refresh button, then something is wrong with database and/or connection settings. Also see end of the comment for logging.

About the **broadcast**: at least that part logs something. Please try stopping the service (i.e. `sudo systemctl stop streamium`) and run it directly from console (assuming it is installed for user `streamium`):
```
sudo su streamium -s /bin/bash
cp /path/to/streamum
./streamium-server
```

Now you should see logs on console, e.g. it should print `Sending [Some XML] to IP:Port` whenever it gets any UDP request. My implementation currently does not really care what comes from where - it just tries to reply with what seems to be "I'm here" in the Streamium protocol. Maybe that's the issue. My MCI200 expects the answer to the broadcast on the same port as it sent the broadcast from, just TCP instead of UDP. That might not be true for your WAS6050, but that could be fixed quite easily.

Final note: if you started the service on console, you should also be able to see the import errors, i.e.:

* `Error on import` translates to "Directory specified in config not found or not readable
* `Not importig /path/to/file.mp3` translates to "Cannot read ID3 tags from file, skipping

**Comment by buitre-buitaker** [comment]
Hi,

More testing...

**Import:** I put just one MP3... and it worked, I put several, maybe 12, and it worked , so I could have a corrupted MP3 file tags, whatever, I will check this part deeply later.

I can manage the database, select favorites, add remote streaming sources, etc... It looks like http server and database, import and all this stuff works nicely now.

**Broadcast:** I don´t get any log messages on console... so the server doesn`t catch any packet... No firewall, so it should be get them... 

Is there any way to sniff the WAS6050 requests? I do not know what protocol uses these devices...

 Thank you!!

**Comment by buitre-buitaker** [comment]
I forgot the pairing process of the stations (WAS6050) with the center. I read carefully the manual:

[https://www.philips.co.uk/c-f/XC000007302/how-to-add-stations-to-my-philips-streamium-center]

> **Add the Station to the network of a Center:**
> 
> - On the Center:
> 
> 1 Ensure the Center is in HD mode.
> 2 Press MENU to enter the menu display.
> 3 Press 3 or 4, then 2 to select Station management (Mgnt).
> 4 Press 3 or 4, then 2 to select Add new Station.
> > The Center searches for the new Station.
> 
> - On the Station:
> 
> 1 Connect the Station to the power supply:
> 2 Turn on the Station.
> If you turn on the Station for the first time, press 3 or 4, then 2 to select the language.
> If you already used the Station with a Center, press MENU, followed by 3 or 4, then 2 to
> select Installation Mode.
> > The display shows: Center found. Setting up. Please wait...
> The display shows: Connecting to Center...
> 
> - On the Center:
> 
> 1 When the Station is found, press STOP 9, to stop the search for the new Station

So, it looks like there is some kind of setup protocol.... interesting.

Do you have any clue on this?

Thanks

**Comment by j-be** [comment]
Hey,

first: I remembered I read some implementations seem to use a different port, i.e. `42951` instead of `42591` (noticed the swapped `5` and `9`). You may want to try that as `ROCKET_PORT` in the `.env` file (everything uses the same port in my implementation, so `ROCKET_PORT` also defines the port it listens for UDP broacasts).

About the setup: the bad news is I never heard ofit, my MCI200 doesn't need it. After reading through the product page I'm starting to suspect this is not the same Streamium protocol my server handles, e.g. I don't think mine is able to play on different clients synchronously. Though, Streamium is a weird protocol, so who knows...

The good news: it seems that your devices support UPnP (sometimes also called DLNA). If that is true you may be better off using a decent UPnP Media Server - I can recommend `minidlna` (no UI, pure console) or `MediaTomb` (has a nice WebUI). Both work well on a RaspberryPi and should be more feature-rich then my implementation - and both should be just a `sudo apt-get install` away. Not sure though, if that would allow you to play on multiple clients synchronously.

In case you want to dig deeper: I used `WireShark` to sniff what goes over the network. It works well for broadcast, as any device on the network gets them. It becomes more difficult when sniffing for other stuff: You either need to run it on one of the communicating devices (I ran my server on my PC while developing anyway), or you can sniff WiFi connections if you have the right WiFi dongle (i.e. Monitor mode has to be supported). It seems the RaspberryPi's (assuming an RPi 3 or 4) WiFi module supports this, so you could go that route. I see the below as my MCI200 sends out the UDP broadcast:
![image](https://user-images.githubusercontent.com/8503582/79066599-7c094e00-7cb9-11ea-89b3-546b536c61f3.png)

Finally, in case that all is not an option, you may get lucky with https://volumio.org/. Assuming you have Volumio up and running on your RaspberryPi you should be able to expose its audio output as MP3 stream on the network using the RTSP protocol (I did that before, I used an "ALSA loopback device" to grab the audio output and VLC to grab it, encode it as MP3 and expose it as RTSP). Then, point your WAS6050 to that stream, e.g. using UPnP. Assuming Philips does little to no fancy synchronization Voodoo on the Streamium Center, that could even enable you to play synchronously on multiple devices - RTSP was designed in that direction.

EDIT: I am starting to suspect that Streamuim Center is doing something like that, i.e. provide the music as RTSP stream (or similar, hopefully without fancy Voodoo) and take control of the satellites using the UPnP Control Point protocol. If that is true: all of this should be achievable using OpenSource software and a RaspberryPi. It would even allow you to control your system with any UPnP/DLNA enabled app on your mobile phone :smile:
